name: Generated APK AAB (Trustrium Build)

env:
  main_project_module: app
  playstore_name: Trustrium
  build_output_path: buildActionResult

on:
  push:
    branches:
      - 'main' # یا آپ کی ڈیفالٹ برانچ کا نام
      - 'release/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set current date
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Set repository name
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - name: Set Up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      # ہم نے یہاں سے "./gradlew build" ہٹا دیا ہے تاکہ ایرر نہ آئے
      # براہ راست APK بنانا شروع کریں

      - name: Build APK Debug
        run: ./gradlew assembleDebug

      - name: Build APK Release
        run: ./gradlew assembleRelease

      - name: Build Bundle (AAB)
        run: ./gradlew :${{ env.main_project_module }}:bundleRelease

      - name: Upload APK Debug
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.date_today }} - APK-Debug
          path: ${{ env.main_project_module }}/build/outputs/apk/debug/

      - name: Upload APK Release
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.date_today }} - APK-Release
          path: ${{ env.main_project_module }}/build/outputs/apk/release/

      - name: Upload AAB Release
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.date_today }} - AAB-Release
          path: ${{ env.main_project_module }}/build/outputs/bundle/release/

      # ======================================================
      # Copy Build Outputs & Push to GitHub
      # ======================================================

      - name: Create build directory
        run: |
          rm -rf ${{ env.build_output_path }}
          mkdir -p ${{ env.build_output_path }}

      - name: Copy files to output folder
        run: |
          find . -name "*.apk" -exec cp {} ${{ env.build_output_path }}/ \;
          find . -name "*.aab" -exec cp {} ${{ env.build_output_path }}/ \;

      - name: Commit & Push build outputs
        run: |
          git config user.name '${{ github.actor }}'
          git config user.email '${{ github.actor }}@users.noreply.github.com'
          git add ${{ env.build_output_path }}/ -f
          git diff --cached --quiet && echo "No changes" || (git commit -m "Build: ${{ env.date_today }} [skip ci]" && git push)
